server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://42.192.75.96:3306/oriental_blog?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: oriental_blog
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.oriental.backend.pojo

sa-token:
  # token?? (????cookie??)
  token-name: orientalToken
  # token??????s ??30?, -1??????
  timeout: 604800
  # token????? (???????????token??) ??: ?
  activity-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: true
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: true
  # token??
  token-style: uuid
  # ????????
  is-log: false